languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Rahul Singhal"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # Explicitly disable main sections so the theme
  # doesn't auto-generate nav links like "Blog".
  mainSections = []
  # description = "My awesome website"



