# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "slate"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false
enableImageLazyLoading = true

# robots = ""
fingerprintAlgorithm = "sha256"

[author]
  name = "Rahul Singhal"
  image = "img/website_pfp.png"
  links = [
    { email = "mailto:rahuls3402@gmail.com" },
    { linkedin = "https://linkedin.com/in/rahul3402/" },
    { twitter = "https://x.com/rahul3426" },
    { github = "https://github.com/rahul3402" } ]
  headline = "I'm a researcher at Distyl AI. Models tend to perform well on evaluations but often fall short in deployment â€” I'm working to close that gap.<br><br>Some of my past experiences include training an internal LLM to improve company-wide workflows, and research on code-generation models. Feel free to reach out at **rahuls3402@gmail.com** to chat!"
  
    

[header]
  layout = "custom" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/dark-logo.jpg"
  showTitle = false

[footer]
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = false
  recentLimit = 5

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

# [fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

# [plausibleAnalytics]
  # domain = "blog.yoursite.com"
  # event = ""
  # script = ""

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
